# 4.2.17 Ensure SSH MaxStartups is configured

- name: Set MaxStartups to 10:30:60
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^(?i)\s*#?MaxStartups\s*'
    line: 'MaxStartups 10:30:60'
    state: present

- name: Comment out MaxStartups setting greater than 10:30:60
  shell: |
    grep -Pi '^\s*maxstartups\s+(((1[1-9]|[1-9][0-9][0-9]+):([0-9]+):([0-9]+))|(([0-9]+):(3[1-9]|[4-9][0-9]|[1-9][0-9][0-9]+):([0-9]+))|(([0-9]+):([0-9]+):(6[1-9]|[7-9][0-9]|[1-9][0-9][0-9]+)))' /etc/ssh/sshd_config/etc/ssh/sshd_config.d/*.conf | while read -r l_out; do sed -ri "/^\s*MaxStartups\s+(((1[1-9]|[1-9][0-9][0-9]+):([0-9]+):([0-9]+))|(([0-9]+):(3[1-9]|[4-9][0-9]|[1-9][0-9][0-9]+):([0-9]+))|(([0-9]+):([0-9]+):(6[1-9]|[7-9][0-9]|[1-9][0-9][0-9]+)))/s/^/# /" "$(awk -F: '{print $1}' <<< $l_out)";done

- name: Restart SSH service
  service:
    name: sshd
    state: restarted
