# 5.1.2.3 Ensure journald is configured to compress large log files (Automated)

- name: Add Compress=yes to journald.conf
  lineinfile:
    path: /etc/systemd/journald.conf
    line: "Compress=yes"
    state: present

- name: Restart systemd-journald.service
  service:
    name: systemd-journald.service
    state: restarted
