# 5.1.1.3 Ensure journald is configured to send logs to rsyslog

- name: Add ForwardToSyslog=yes to journald.conf
  lineinfile:
    path: /etc/systemd/journald.conf
    line: "ForwardToSyslog=yes"
    state: present

- name: Restart rsyslog
  service:
    name: rsyslog
    state: restarted
