# 5.1.2.4 Ensure journald is configured to write logfiles to persistent disk (Automated)

- name: Add Storage=persistent to journald.conf
  lineinfile:
    path: /etc/systemd/journald.conf
    line: "Storage=persistent"
    state: present

- name: Restart systemd-journald.service
  service:
    name: systemd-journald.service
    state: restarted
