# 5.2.4.3 Ensure only authorized groups are assigned ownership of audit log files

- name: Get the audit log directory
  shell: awk -F"=" '/^\s*log_file\s*=\s*/ {print $2}' /etc/audit/auditd.conf
  register: audit_log_dir
  changed_when: false
  ignore_errors: yes

- name: Set audit log file ownership to adm group
  find:
    paths: "{{ audit_log_dir.stdout | dirname }}"
    patterns: "*"
    recurse: yes
    excludes: "! -group adm,! -group root"
  register: audit_files

- name: Set ownership of /var/log/audit/ to adm group
  file:
    path: /var/log/audit/
    owner: root
    group: adm
    state: directory
  become: yes
  when: "'adm' not in (audit_files.files | map(attribute='item.group'))"

- name: Set log_group parameter in auditd.conf to log_group = adm
  replace:
    path: /etc/audit/auditd.conf
    regexp: '^\s*#?\s*log_group\s*=\s*\S+(\s*#.*)?.*$'
    replace: 'log_group = adm\1'
