# 5.2.4.6 Ensure audit configuration files are owned by root

- name: Find audit configuration files
  find:
    paths: /etc/audit/
    patterns: "*.conf,*.rules"
    recurse: yes
  register: audit_config_files

- name: Change ownership to root
  file:
    path: "{{ item.path }}"
    owner: root
    state: file
  with_items: "{{ audit_config_files.files }}"
